workflows:
version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run: yarn global add node-gyp
      - run: yarn install
      - run: yarn lint
      - run: yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lcok" }}
          paths:
            - ./node_modules
